// Template: AUTH_SETUP.md content generator with project-specific URLs.

export function authSetupMarkdown(opts: { localUrl: string; productionUrl?: string }): string {
  const prod = opts.productionUrl ?? "https://YOUR-APP.vercel.app";
  return `# Supabase Auth Setup

This file was generated by setup-agent. Follow these steps once in the Supabase
dashboard to finish wiring up authentication.

## 1. Required environment variables

Make sure these exist in \`.env.local\` (setup-agent can add placeholders for you):

- \`NEXT_PUBLIC_SUPABASE_URL\` — your project URL (safe for the browser)
- \`NEXT_PUBLIC_SUPABASE_ANON_KEY\` — the anon/public key (safe for the browser)
- \`SUPABASE_SERVICE_ROLE_KEY\` — **server only**, never expose to the browser

## 2. Auth settings (Supabase Dashboard → Authentication → URL Configuration)

- **Site URL:** \`${prod}\`
- **Redirect URLs (add all that apply):**
  - \`${opts.localUrl}/**\` (local development)
  - \`${prod}/**\` (production on Vercel)

If you use preview deployments, also add:
  - \`https://*-YOUR-TEAM.vercel.app/**\`

## 3. Local development URL

While developing, your app runs at:

- \`${opts.localUrl}\`

Make sure this exact URL is in the redirect list above, or logins will fail with
a redirect error.

## 4. Vercel URL guidance

After you deploy, copy your production URL from Vercel and make sure it matches
the **Site URL** and is included in the **Redirect URLs** above.

## 5. Provider setup

Enable the sign-in providers you want (Email, Google, GitHub, etc.) under
**Authentication → Providers**. For OAuth providers you'll paste a client ID and
secret from that provider — keep those secret and never commit them.
`;
}
